### ISSUE TITLE
Ardis login via SPID

### ISSUE THREAD

**Issue by Alrubin** [studentreps/vademecum#12]
Apparently, the new procedure to get access to the Ardis account is via SPID (the Italian Digital Identity). We need to change the procedure described in the vademecum. Hint: ask Bertossa.

**Comment by matteosecli** [comment]
@rikigigi

**Comment by fcaleffi** [comment]
Small disclaimer: this weekend I'll take care of all the open issues.

**Comment by rikigigi** [comment]
Sorry, it was announced this summer, but apparently I missed/forgotten the part that writes about the new procedure
http://www.ardis.fvg.it/contenuti.php?view=news&id=10083&tipo=evidenza

we should add a section on how to get the SPID

**Comment by fcaleffi** [comment]
For the time being, I've expanded the section regarding the ARDiS online form in Chapter 11 with a brief description of the SPID logic and how to obtain it. If you wish, have a look at it!

**Comment by matteosecli** [comment]
Thank you, Fabio! Btw, for a fully online SPID process (no need to go to Poste, your identity can be validated with a Facebook or WhatsApp call, or with you CIE via an app), I suggest SIELTE. It's one of the few with the top-level SPID authentication, together with Poste. Comparison between providers here: https://www.spid.gov.it/cos-e-spid/come-scegliere-tra-gli-idp/ (English: https://www.spid.gov.it/en/what-is-spid/how-to-choose-between-digital-identity-providers/ )

**Comment by fcaleffi** [comment]
Many thanks, Matteo! I didn't know that SIELTE is that good, I'll recommend it explicitly in the Vademecum.
