### ISSUE TITLE
Music room info

### ISSUE THREAD

**Issue by sonarventu** [studentreps/vademecum#14]
The music room section contains obsolete info. The drums are not there anymore, and the Student Secretariat is not who people should contact in order to be inserted in the Calendar: Riccardo Iancer does not take care of this anymore. At the moment, I am temporarily the one they should contact at dventure@sissa.it

**Comment by fcaleffi** [comment]
I've partially taken care of the due updates in the last release, I didn't know about the drums (sigh)... As soon as possible, I'll come back to it. Are the electric guitar and bass still there? What about the amplifiers?

**Comment by sonarventu** [comment]
There is an electric something still there, I don't remember if it's a guitar or a bass (I'll check later) because I didn't know it had been made available for everyone. There is also a number of personal instruments people just leave there, so I would say as a general rule that instruments in their case should be interpreted as personal.
There are indeed a few amplifiers people can just use, and of course the piano is still there. There were plans of buying a new drumset, but I have no news about it.
Davide


Davide Venturelli
SISSA - International School for Advanced Studies
Via Bonomea 265, 34136 Trieste, Italy
Office: building A, room 603
________________________________

**Comment by fcaleffi** [comment]
Hi Davide, do you have any news about the presence of an electric guitar/bass and the arrival of a new drumset? In the meanwhile, I'll mention a few things you pointed out in the last message.

**Comment by sonarventu** [comment]
Hi Fabio,
no news since last time. There is no new drumset and the two guitars in the room are not “public”, to the best of my knowledge (one is mine, in fact!)…
Davide

Davide Venturelli
SISSA - International School for Advanced Studies
Via Bonomea 265, 34136 Trieste, Italy
Office: building A, room 603
________________________________
