### ISSUE TITLE
links to SEPA member states

### ISSUE THREAD

**Issue by iprusak** [studentreps/vademecum#17]
The links to SEPA member states need to be updated, at the moment that both refer to the same page with some info in italian, and it's not cleaat all where to look . I'd rather use this one
https://www.ecb.europa.eu/paym/integration/retail/sepa/html/index.en.html

**Comment by fcaleffi** [comment]
You're right, that link is unuseful as it is. I'll insert the website that you suggested on Overleaf and commit the change, the issue will remain open in case you want to add more!

**Comment by iprusak** [comment]
> You're right, that link is unuseful as it is. I'll insert the website that you suggested on Overleaf and commit the change, the issue will remain open in case you want to add more!

thanks!
