### ISSUE TITLE
Missions

### ISSUE THREAD

**Issue by Alrubin** [studentreps/vademecum#19]
We should specify that after our battle, it is possible to cumulate fundings for trips abroad and that the minimum limit of days for the increase of 50% of the fellowship has passed from 30 days to 14 days.

**Comment by fcaleffi** [comment]
Hi Ale,
I've just jotted down some lines on this in Sec. 3.3 on the Vad, if you're fine with them I think I'll give out a new release (some other small changes have been made since the last release).
