### ISSUE TITLE
Put order in the table of contents

### ISSUE THREAD

**Issue by Alrubin** [studentreps/vademecum#2]
Dear all, 

the Vademecum has rapidly grown and I believe that the proposed material should be reorganised. First of all I propose to:

1) Split section 5.4 (music room and Kindergarten) and append "Music Room" to "Extracurricular activities" and "Kindergarten" to  "SISSA support and Contribution"
2) Rename section 4.3 (After you get your PH.D.) with "SISSA Alumni Society" 
3) Split the long list of chapter 6 into sections and note that 
      -  the point about INPS benefits must be moved in the proper chapter
      -  the 1000 euros contribution towards expenses for training and research is a national rule so I would move this part into                 
          chapter 4 (as part of research activities and missions)
4) Add a Chapter about ILAS
5) Add a Chapter about ITCS services and Ulisses

In this sense, I propose further to reorder the chapters under a "bigger" classification in Parts according to the following categories: 

1) Introduction (chapters 1 and 2) - not mandatory
2) Life at SISSA (chapters 4,5,9 and 13)
3) Discounts, Support and Contributions (chapters 3,6,7,8) 
4) Other Administrative Services (Chapters 10,11,12 and 14)

This further subdivision can be easily created just in the table of contents and not in the full text using the comand "\addcontentsline{toc}{part}{Title of the part}" together with the following strings which I recommend in the LateX class . What this code does is a little surprise ;)

```latex
\usepackage{titlesec}
\usepackage{titletoc}
\usepackage{chngcntr}
\usepackage{fmtcount}
\titlecontents{part}[0em]{\large\bfseries\protect\addvspace{25pt}\titlerule\addvspace{1ex}}%
{ }{}%
{\hfill\contentspage}[\addvspace{0.5ex}\titlerule\addvspace{1ex}]%
```

**Comment by matteosecli** [comment]
This should have been addressed by https://github.com/studentreps/vademecum/pull/4 and https://github.com/studentreps/vademecum/pull/5, so I'm gonna close; feel free to reopen if needed.

Thank you @Alrubin for all the work! 🎉 🚀
