### ISSUE TITLE
Indennità di Disoccupazione

### ISSUE THREAD

**Issue by Alrubin** [studentreps/vademecum#20]
Il paragrafetto alla fine del capitolo 10 è stringato e non aggiornato (alcune cose sono recentemente cambiate, tipo la durata che passa da 6 mesi a 12 mesi). Propongo di toglierlo e contestualmente una creare nuova sezione nel capitolo 4 chiamata "Indennità di Disoccupazione" in cui si spiega per bene la questione. Maggiori dettagli alla pagina INPS: https://www.inps.it/prestazioni-servizi/dis-coll-indennita-mensile-di-disoccupazione 

NB LA DISOCCUPAZIONE NON PARTE DALLA DISCUSSIONE DI DOTTORATO DA MA QUANDO FINISCE IL CONTRATTO. Per esempio, se il contratto finisce il 30 settembre e si discute il 7 Ottobre, la domanda di disoccupazione si può fare dal 1 Ottobre. In particolare, il contributo è erogato dal giorno della domanda e quindi più tardi la fai meno soldi ottieni.

**Comment by fcaleffi** [comment]
Grazie Ale per aver sollevato la cosa, correggerò la parte interessata quanto prima.

**Comment by fcaleffi** [comment]
@rikigigi, te ne stai già occupando tu?

**Comment by rikigigi** [comment]
c'è la pull request https://github.com/studentreps/vademecum/pull/22 che ha una bozza, è da scrivere meglio

**Comment by fcaleffi** [comment]
Grazie a @rikigigi, possiamo ora chiudere questa issue.
